name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: google-services.json
      working-directory: ./code/app
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -di > google-services.json
    - name: Build with Gradle and Unit Test
      working-directory: ./code
      run: ./gradlew build
    - name: Unit Test
      working-directory: ./code
      run: ./gradlew test
