name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: git secret
      run: |
        git clone https://github.com/sobolevn/git-secret.git git-secret
        cd git-secret && make build
        PREFIX="/usr/local" make install
        cd ..
        gpg --import <(echo "${{ secrets.GITHUB_GPG_SECRET }}")
        git secret reveal
    - name: Build with Gradle and Unit Test
      working-directory: ./code
      run: ./gradlew build
    - name: Hide secret
      run: git secret hide -d
